sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rafaelsanzio/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rafaelsanzio/docker-react npm run test
